name: Build & Admin
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{secrets.SSH_USERNAME}} # User of the server you want to ssh into
          password: ${{secrets.SSH_PASSWORD}}
    
          script: |
            cd airjadli-client
          
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install --lts
            node -v
            npm -v
            npm i pm2@latest -g
            rm -rf node_modules package-lock.json
            npm i 
            npm run build
            pm2 delete  client
            pm2 start 'npm start' --name client
            echo 'Deployment successful to digital ocean' 